#!/usr/bin/env python3

"""
Proxy Project
"""

from socket import socket
import os
from select import select

def server(port):
    """Main"""
    sock = socket() #default is AF_INET, SOCK_STREAM
    sock.bind(('localhost', port))
    sock.listen(5)
    while True:
        try:
            clnt_sock, _ = sock.accept()
        except KeyboardInterrupt:
            break
        clnt_sock.set_inheritable(True)
        if os.fork() == 0: #child process (0)
            try:
                while True: #loop until an interrupt is received
                    child_sock = socket()
                    child(clnt_sock, child_sock)
                    child_sock.close()
            except (KeyboardInterrupt, ConnectionError):
                pass
            child_sock.close()
            clnt_sock.close()
            os._exit(0) #pylint: disable=protected-access
        clnt_sock.close()
        while os.waitpid(-1, os.WNOHANG) != (0, 0):
            pass
    sock.close()

def child(clnt_sock, serv_sock):
    """Child process"""
    msg, headers = parse_headers(clnt_sock)
    host = headers['host'].split(':')
    address = host[0]
    if len(host) == 2: #contains port number
        port = int(host[1])
    else:
        port = 80
    #recv from client (web browser) and send to server (web server)
    serv_sock.connect((address, port))
    transfer_data(serv_sock, clnt_sock, headers, msg)
    #recv from server (web server) and send to client (web browser)
    msg, headers = parse_headers(serv_sock)
    transfer_data(clnt_sock, serv_sock, headers, msg)

def transfer_data(to_sock, from_sock, headers, msg):
    """Transfer data from a receiving socket to a sending socket"""
    total_bytes = 0
    end_found = check_end(headers, msg)
    while not end_found or total_bytes < len(msg):
        if not end_found and total_bytes < len(msg): #still need to receive and send data
            recv, send, _ = select([from_sock], [to_sock], [])
            if recv:
                try:
                    msg += socket_recv(from_sock)
                except ConnectionAbortedError:
                    end_found = True
                else:
                    end_found = check_end(headers, msg)
            if send:
                total_bytes += to_sock.send(msg[total_bytes:])
        elif not end_found: #still need to receive data
            try:
                msg += socket_recv(from_sock)
            except ConnectionAbortedError:
                end_found = True
            else:
                end_found = check_end(headers, msg)
        else: #data left to send
            total_bytes += to_sock.send(msg[total_bytes:])
    print(msg.split(b'\r\n\r\n', 1)[1]) #prints body

def socket_recv(sock):
    """Used to catch the error that the connection has been severed"""
    msg = sock.recv(4096)
    if len(msg) == 0:
        raise ConnectionAbortedError('Sender closed the socket')
    return msg

def check_end(headers, msg):
    """Check for finding the end of the message body"""
    if 'transfer-encoding' in headers and headers['transfer-encoding'] == 'chunked':
        body = msg.split(b'\r\n\r\n', 1)[1]
        current_position = 0
        while current_position < len(body):
            #split on first instance of '\r\n'
            index_after_size = body.find(b'\r\n', current_position)
            if index_after_size == -1:
                return False
            chunk_size = int(body[current_position:index_after_size], 16)
            if chunk_size == 0 and len(body) == index_after_size + 4: #index + '\r\n' + '\r\n'
                return True
            current_position = index_after_size + chunk_size + 4
        return False
    elif 'content-length' in headers:
        if int(headers['content-length']) > len(msg.split(b'\r\n\r\n', 1)[1]):
            return False
        return True
    return True

def parse_headers(sock):
    """Parse Headers"""
    msg = b''
    headers = {}
    while b'\r\n\r\n' not in msg: #find separation of body and headers
        msg += socket_recv(sock)
    #convert byte string to acscii
    headerlines = msg.split(b'\r\n\r\n', 1)[0].decode('US-ASCII').split('\r\n')
    print(headerlines[0])
    for line in headerlines[1:]:
        print(line)
        header = line.split(':', 1) #split on first instance of ':'
        if len(header) == 2:
            headers[header[0].strip().lower()] = header[1].strip() #strip whitespace
    return msg, headers

if __name__ == '__main__':
    import sys
    if len(sys.argv) == 2:
        server(int(sys.argv[1]))
    else:
        print('Incorrect parameters')
